# Generated by Django 5.2.5 on 2025-09-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('complain', models.CharField(choices=[('Water', 'Water Supplay'), ('Electricity', 'Electricitiy'), ('Road/infrastructure', 'Road/infrastructure'), ('Sanitation', 'Sanitation'), ('other', 'other')], default='Water')),
                ('Complaint_Details', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
