# Generated by Django 5.2.5 on 2025-09-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain',
            field=models.CharField(choices=[('Water', 'Water Supply'), ('Electricity', 'Electricity'), ('Road', 'Road / Infrastructure'), ('Sanitation', 'Sanitation'), ('Other', 'Other')], default='Water', max_length=50),
        ),
    ]
