# Generated by Django 5.2.5 on 2025-09-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
    ]
