# Generated by Django 5.2.5 on 2025-09-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0003_event_alter_contact_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='short_description',
        ),
    ]
