# Generated by Django 5.2.5 on 2025-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0005_celebrity_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'db_table': 'Gallery',
            },
        ),
        migrations.AlterModelTable(
            name='celebrity',
            table='Celebrity',
        ),
    ]
