# Generated by Django 5.2.5 on 2025-09-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0007_gallery_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_mem_name', models.CharField(max_length=100)),
                ('staff_mem_position', models.CharField(max_length=50)),
                ('staff_mem_contact', models.CharField(max_length=10)),
                ('staff_mem_image', models.ImageField(upload_to='staffs/')),
            ],
            options={
                'db_table': 'staffs_img',
            },
        ),
    ]
