# Generated by Django 5.2.5 on 2025-09-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0008_staffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_position', models.CharField(max_length=50)),
                ('member_contact', models.CharField(max_length=10)),
                ('member_image', models.ImageField(upload_to='members/')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
