# Generated by Django 5.2.5 on 2025-09-13 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0008_development_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
