# Generated by Django 5.2.5 on 2025-09-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0009_development_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infrastructure',
            old_name='extra_point',
            new_name='extra_points',
        ),
    ]
