# Generated by Django 5.2.5 on 2025-09-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0009_members'),
        ('gram_panchayat', '0010_rename_extra_point_infrastructure_extra_points'),
    ]

    operations = [
    ]
