# Generated by Django 5.2.5 on 2025-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0011_merge_20250918_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sarpanch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarpanch_name', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('phono_no', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('point', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
