# Generated by Django 5.2.5 on 2025-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0012_sarpanch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarpanch',
            old_name='point',
            new_name='points',
        ),
        migrations.AlterField(
            model_name='sarpanch',
            name='phono_no',
            field=models.CharField(max_length=10),
        ),
    ]
