# Generated by Django 5.2.5 on 2025-09-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0013_rename_point_sarpanch_points_alter_sarpanch_phono_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarpanch',
            name='sarpanch_image',
            field=models.ImageField(default=1, upload_to='sarpanch/'),
            preserve_default=False,
        ),
    ]
