# Generated by Django 5.2.5 on 2025-09-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0014_sarpanch_sarpanch_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarpanch',
            old_name='points',
            new_name='extra_points',
        ),
    ]
