# Generated by Django 5.2.5 on 2025-09-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0015_rename_points_sarpanch_extra_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarpanch',
            old_name='phono_no',
            new_name='phone_no',
        ),
    ]
