# Generated by Django 5.2.5 on 2025-09-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0016_rename_phono_no_sarpanch_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=300)),
                ('eligibility', models.CharField(max_length=200)),
                ('benifit', models.TextField(max_length=300)),
                ('document_required', models.CharField(max_length=200)),
                ('how_to_apply', models.TextField(max_length=300)),
                ('crated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
