# Generated by Django 5.2.5 on 2025-09-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0017_scheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
