# Generated by Django 5.2.5 on 2025-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0018_rename_crated_at_scheme_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='benifit',
            new_name='benefit',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='document_required',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility',
            field=models.TextField(max_length=300),
        ),
    ]
