# Generated by Django 5.2.5 on 2025-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0019_rename_benifit_scheme_benefit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GramSabhaMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('agenda', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('minutes_file', models.FileField(blank=True, null=True, upload_to='minutes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
