# Generated by Django 5.2.5 on 2025-09-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0020_gramsabhameeting'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sarpanch',
            table='sarpanch',
        ),
    ]
