# Generated by Django 5.2.5 on 2025-09-30 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0021_alter_sarpanch_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gramsabhameeting',
            table='gramsabha',
        ),
        migrations.AlterModelTable(
            name='scheme',
            table='scheme',
        ),
    ]
