# Generated by Django 5.2.5 on 2025-09-30 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0022_alter_gramsabhameeting_table_alter_scheme_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complain',
            table='complain',
        ),
    ]
