<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-10-05 13:37
=======
# Generated by Django 5.2.5 on 2025-10-06 08:08
>>>>>>> 8855c1e69928240542da8e6bcb6bfd8eabd65b7c

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0020_feedback'),
        ('gram_panchayat', '0024_document'),
    ]

    operations = [
    ]
