# Generated by Django 5.2.5 on 2025-10-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0020_feedback'),
        ('gram_panchayat', '0024_document'),
    ]

    operations = [
    ]
