# Generated by Django 5.0.3 on 2025-10-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0025_merge_0020_feedback_0024_document'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffs',
            table='staffs',
        ),
    ]
