# Generated by Django 5.2.5 on 2025-10-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0025_merge_0020_feedback_0024_document'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='celebrity',
            table='celebrity',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='development',
            table='development',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='gallery',
            table='gallery',
        ),
        migrations.AlterModelTable(
            name='infrastructure',
            table='infrastructure',
        ),
    ]
