# Generated by Django 5.0.3 on 2025-10-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0026_alter_staffs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='Feedback',
        ),
    ]
