# Generated by Django 5.2.5 on 2025-10-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0027_history_alter_staffs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='imgage',
            field=models.ImageField(default=1, upload_to='history/'),
            preserve_default=False,
        ),
    ]
