# Generated by Django 5.2.5 on 2025-10-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0028_history_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
