# Generated by Django 5.2.5 on 2025-10-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0029_rename_create_at_history_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='imgage',
            new_name='image',
        ),
    ]
