# Generated by Django 5.2.5 on 2025-11-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0027_alter_feedback_table'),
        ('gram_panchayat', '0030_rename_imgage_history_image'),
    ]

    operations = [
    ]
