# Generated by Django 5.2.5 on 2025-11-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayat', '0031_merge_20251109_1325'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='gramsabhameeting',
            table='Gramsabha',
        ),
    ]
